version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=user
    ports:
      - '27017:27017'
