version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_DATABASE=testDatabase
    ports:
      - '27017:27017'
